trigger:
 - main

 pool:
   vmImage: 'ubuntu-latest' 

 variables:
   imageName: 'pipelines-javascript-docker'

 steps:
 - task: Docker@2
   displayName: Build an image
   inputs:
     repository: $(imageName)
     command: build
     dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
     buildContext: '$(Build.SourcesDirectory)'
     #Dockerfile: Dockerfile 
     
     
#      stages:
# - stage: Docker
#   displayName: Build & Push Docker image to AWS ECR
#   jobs:
#   - job: Build_and_Push
#     displayName: Build & Push Docker image
#     pool:
#       vmImage: ubuntu-latest
#     steps:
#     - task: Docker@2
#       displayName: Build an image
#       inputs:
#         command: build
#         dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
#         buildContext: '$(Build.SourcesDirectory)'
#         repository: $(DOCKER_REPOSITORY_NAME)
