trigger:
- main

resources:
- repo: self

variables:
  imageRepo: eagunuworld/azure-demo
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        containerRegistry: 'eagunuworld_dockerhub_azure_creds'
        repository: '$(imageRepo)'
        command: 'buildAndPush'
        Dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        tags: |
          $(tag)
          latest
    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: '$(Pipeline.Workspace)/s/azure-aks.yaml'
        artifact: 'manifests'
        publishLocation: 'pipeline'
        
- stage: Deploy
  displayName: Deploy to Dev
  dependsOn: Build
  variables:
    dockerhub-secret: myacrsecretconnection
    dockerurl: 'hub.docker.com'
  jobs:
  - deployment: Deploy
    displayName: Deploy to AKS
    environment: 'cka-default.default'
    pool: 
      vmImage: ubuntu-latest
    strategy:
      runOnce:
        deploy:
          steps:
          - task: DownloadPipelineArtifact@2
            inputs:
              buildType: 'current'
              artifactName: 'manifests'
              targetPath: '$(Pipeline.Workspace)/manifests'
          - task: KubernetesManifest@0
            inputs:
              action: 'createSecret'
              #kubernetesServiceConnection: 'eagunuworld_gke_clusters_creds'
              namespace: 'default'
              secretType: 'dockerRegistry'
              secretName: '$(dockerhub-secret)'
              dockerRegistryEndpoint: 'eagunuworld_dockerhub_azure_creds'
          - task: KubernetesManifest@0
            inputs:
              action: 'deploy'
              namespace: 'default'
              manifests: |
                $(Pipeline.Workspace)/manifests/azure-aks.yaml
              containers: '$(dockerurl)/$(imageRepo):$(tag)'
              imagePullSecrets: '$(dockerhub-secret)'
