apiVersion: apps/v1
kind: Deployment
metadata:
  name: prod-ns-pod
spec:
  replicas: 2
  selector:
    matchLabels:
      app: prod-ns-pod
  template:
    metadata:
      labels:
        app: prod-ns-pod
    spec:
      containers:
      - name: prod-ns-con
        image: eagunuworld/azure-demo:178
        ports:
        - containerPort: 5000
# service type loadbalancer       
---
apiVersion: v1
kind: Service
metadata:
  name: prod-ns-svc
spec:
  selector:
    app: prod-ns-pod
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: LoadBalancer
