apiVersion: apps/v1
kind: Deployment
metadata:
  name: staging-pod
spec:
  replicas: 2
  selector:
    matchLabels:
      app: staging
  template:
    metadata:
      labels:
        app: staging
    spec:
      containers:
      - name: staging-con
        image: eagunuworld/azure-demo:186
        ports:
        - containerPort: 5000
# service type loadbalancer       
---
apiVersion: v1
kind: Service
metadata:
  name: staging-svc
spec:
  selector:
    app: staging
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: LoadBalancer
